trainer:
  name: flowbp_lagrange
model:
  pretrained_model_name_or_path: data/flux
  gradient_checkpointing: true
  master_weight_type: bf16
  use_ema: true
  ema_decay: 0.995
data:
  data_json_path: data/rl_embeddings/videos2caption.json
  num_latent_t: 1
  cfg: 0.0
  dataloader_num_workers: 8
train:
  seed: 42
  train_batch_size: 8
  train_sp_batch_size: 8
  gradient_accumulation_steps: 1
  max_train_steps: 300
  checkpointing_steps: 100
  output_dir: outputs/final/flux1/flux1_flowbp_lagrange
  allow_tf32: true
optimizer:
  learning_rate: 1.0e-05
  weight_decay: 0.0001
  lr_warmup_steps: 0
  max_grad_norm: 1.0
distributed:
  sp_size: 1
  fsdp_sharding_startegy: full
sampling:
  h: 512
  w: 512
  rollout_steps: 25
  sampling_steps: 25
  sampler_seed: 1223627
  cfg_guidance: 4.0
reward:
  use_hpsv2: true
  loss_relu_clip: 0.55
  loss_grad_scale: 1.0
flowbp:
  select_idx_seed: 114
  min_idx: 1
  max_idx: 26
  jk_sampling_mode: dirichlet
  jk_dirichlet_alpha_a: 2.5
  jk_dirichlet_alpha_b: 6.0
  jk_dirichlet_alpha_c: 2.0
flowbp_lagrange:
  alpha: 0.1
  tau: 0.2
  connector_order: 3
  detach_history: true
  grad_support_mode: midpoint
  grad_support_scale: 0.25
  max_active_supports: 2
  grad_rescale: 0.5
  weight_scheme: lagrange
  debug_connector: false
  anchor_lambda: 1.0
eval:
  evaluation_interval: 50
  prompts_file: ./assets/eval_prompts.txt
  num_imgs_per_prompt: 1
  seed: 42
  num_steps: 50
  guidance_scale: 4.0
  reward_ckpt_path: models/reward_ckpts
  reward_fn:
    clipscore: 1.0
    hpsv2: 1.0
    pickscore: 1.0
    imagereward: 1.0
logging:
  project: flowbp
